[project]
name = "speaky"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "load-dotenv>=0.1.0",
    "openai[voice-helpers]>=1.98.0",
    "pyaudio>=0.2.14",
    "python-vlc>=3.0.21203",
    "pyttsx3>=2.99",
]
